/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.salao.telas;

import java.sql.*;
import br.com.salao.dal.ModuloConexao;
import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.BorderFactory;
import javax.swing.UIManager;

/**
 *
 * @author yukii
 */
public class TelaLogin extends javax.swing.JFrame {
    
    //usando a variavel conexao DAL
    Connection conexao = null;
    //Criando variaveis para conectar com o banco
    //Prepared Statement e ResultSet são frameworks do pacote java.sql e servem para executar as instruções sql
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public void logar() {
        String sql = "select * from USUARIOS where login=? and senha=?";
        try {
            //as linhas abaixo preparam a consulta ao banco em função do
            //que foi digitado nas caixas de texto. O ? é substituido pelo conteudo das variaveis
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtUsuario.getText());
            String captura = new String(txtSenha.getPassword());
            pst.setString(2, captura);
            //a linha abaixo executa a query 
            rs = pst.executeQuery();
            //se existir usuario e senha correspondente
            if (rs.next()) {
                //abaixo obrtemos o conteúso do campo perfil
                String perfil=rs.getString(5);
                //abaixo, faz o tratamento do perfil usuario
                if(perfil.equals("admin")){
                    TelaPrincipal principal = new TelaPrincipal();
                    principal.setVisible(true);
                    TelaPrincipal.menRelSer.setEnabled(true);
                    TelaPrincipal.menCadUsu.setEnabled(true);
                     // As linhas abaixo substituem a Label Usuario(lblUsu) pelo nome do usuario ao inicializar
                    TelaPrincipal.lblUsuario.setText(rs.getString(3));
                    TelaPrincipal.lblUsuario.setForeground(Color.red);
                    //abaixo, quando fechar, desloga
                    this.dispose();
                }else{
                    TelaPrincipal principal = new TelaPrincipal();
                    principal.setVisible(true);
                    TelaPrincipal.lblUsuario.setText(rs.getString(3));
                    this.dispose();
                    conexao.close();
                }
                
                //abaixo faz com que a TelaPrincipal apareça na tela (setVisible)
                
                
            } else {
                JOptionPane.showMessageDialog(null, "Usuário ou senha inválido");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        conexao = ModuloConexao.conector();
        //a linha abaixo serve de apoio ao status da conexao
        //System.out.println(conexao);
        try {
                UIManager.setLookAndFeel(new FlatDarculaLaf());
            }catch (Exception e) {
                e.printStackTrace();
            }
        if (conexao != null) {
            lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/salao/icones/dbok.png")));
        } else {
            lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/salao/icones/dberror.png")));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        lblStatus = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(204, 0, 255));
        setFont(new java.awt.Font("Corbel Light", 0, 18)); // NOI18N
        setForeground(java.awt.Color.black);
        setPreferredSize(new java.awt.Dimension(700, 590));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Corbel Light", 0, 18)); // NOI18N
        jLabel1.setText("Usuário");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 90, 56, 23);

        jLabel2.setFont(new java.awt.Font("Corbel Light", 0, 18)); // NOI18N
        jLabel2.setText("Senha");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 150, 46, 23);
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(160, 80, 134, 30);

        btnLogin.setBackground(new java.awt.Color(0, 51, 204));
        btnLogin.setFont(new java.awt.Font("Corbel Light", 1, 13)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 204), 3, true));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(180, 200, 70, 30);

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtSenha);
        txtSenha.setBounds(160, 140, 134, 30);

        lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/salao/icones/dberror.png"))); // NOI18N
        getContentPane().add(lblStatus);
        lblStatus.setBounds(330, 190, 48, 48);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/salao/icones/tesoura.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(330, 40, 48, 48);

        jLabel4.setBackground(new java.awt.Color(255, 51, 204));
        jLabel4.setForeground(new java.awt.Color(204, 102, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Meus Documentos\\Arquivos\\Documentação Salão\\icones\\bordaLogiin.png")); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 153)), null));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 456, 290);

        setSize(new java.awt.Dimension(473, 329));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
        logar();
        
        
    }//GEN-LAST:event_txtSenhaActionPerformed
        
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // chamando o metodo logar
        logar();
        
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
                UIManager.setLookAndFeel(new FlatDarculaLaf());
            }catch (Exception e) {
                e.printStackTrace();
            }
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>
        
        UIManager.put("btnLogin.defaultButtonFollowsFocus", Boolean.TRUE);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
